apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 80
    name: http
  selector:
    run: apigw
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apigw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
        run: apigw
        app: apigw
        service: apigw
        tier: backend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: apigw
        imagePullPolicy: Never
        image: asia.gcr.io/evntsrc-io/apigw:latest
        ports:
        - containerPort: 80