apiVersion: v1
kind: Service
metadata:
  name: metrics
spec:
  ports:
  - port: 443
    name: https
  - port: 80
    name: metrics
  selector:
    run: metrics
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
        run: metrics
        app: metrics
        service: metrics
        tier: backend
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: metrics
        image: asia.gcr.io/evntsrc-io/metrics:latest
        args:
        - metrics
        - start
        env:
        - name: PROM_HOST
          value: "prometheus-server:80"