apiVersion: v1
kind: Service
metadata:
  name: passport
spec:
  ports:
  - port: 443
    name: grpc
  selector:
    run: passport
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: passport
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
        run: passport
        app: passport
        service: passport
        tier: backend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: passport
        imagePullPolicy: Never
        image: asia.gcr.io/evntsrc-io/passport:latest
        ports:
        - containerPort: 443
        env:
        - name: NATS_HOST
          value: "nats:4222"
        volumeMounts:
        - name: certs
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: passport-certs