apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storer
spec:
  replicas: 2
  template:
    metadata:
      labels:
        version: v1
        run: storer
        app: storer
        service: storer
        tier: backend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: storer
        image: asia.gcr.io/evntsrc-io/storer:latest
        args:
        - storer
        - start
        env:
        - name: DB_HOST
          value: "mongo-mongodb.default:27017"
        - name: NATS_HOST
          value: "nats.nats-io:4222"
        - name: PGDB_HOST
          value: "host=cockroach-cockroachdb port=26257 sslmode=disable dbname=event_store"