apiVersion: v1
kind: Service
metadata:
  name: storer
  annotations:
    prometheus.io/path: "/metrics"
spec:
  ports:
  - port: 443
    name: https
  - port: 80
    name: metrics
  selector:
    run: storer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storer
spec:
  replicas: 5
  template:
    metadata:
      labels:
        version: v1
        run: storer
        app: storer
        service: storer
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: storer
        image: asia.gcr.io/evntsrc-io/storer:latest
        args:
        - storer
        - start
        env:
        - name: DB_HOST
          value: "mongo-mongodb.default:27017"
        - name: NATS_HOST
          value: "nats.nats-io:4222"
        - name: PGDB_HOST
          value: "host=cockroach-cockroachdb port=26257 sslmode=disable dbname=event_store"