apiVersion: v1
kind: Service
metadata:
  name: streamauth
spec:
  ports:
  - port: 443
    name: https
  selector:
    run: streamauth
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streamauth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
        run: streamauth
        app: streamauth
        service: streamauth
        tier: backend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: streamauth
        imagePullPolicy: Never
        image: asia.gcr.io/evntsrc-io/streamauth:latest
        ports:
        - containerPort: 443
        env:
        - name: DB_HOST
          value: "mongo-mongodb.default:27017"