apiVersion: v1
kind: Service
metadata:
  name: streams
spec:
  ports:
  - port: 443
    name: https
  selector:
    run: streams
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streams
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
        run: streams
        app: streams
        service: streams
        tier: backend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: streams
        imagePullPolicy: Never
        image: asia.gcr.io/evntsrc-io/streams:latest
        ports:
        - containerPort: 443