apiVersion: v1
kind: Service
metadata:
  name: ttlscheduler
spec:
  ports:
  - port: 443
    name: https
  selector:
    run: ttlscheduler
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ttlscheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
        run: ttlscheduler
        app: ttlscheduler
        service: ttlscheduler
        tier: backend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: ttlscheduler
        image: asia.gcr.io/evntsrc-io/ttlscheduler:latest
        ports:
        - containerPort: 443