apiVersion: v1
kind: Service
metadata:
  name: websocks
spec:
  ports:
  - port: 80
    name: http
  selector:
    run: websocks
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websocks
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
        run: websocks
        app: websocks
        service: websocks
        tier: backend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: websocks
        image: asia.gcr.io/evntsrc-io/websocks:latest
        ports:
        - containerPort: 80
        args:
        - websocks
        - serve
        env:
        - name: NATS_HOST
          value: "nats.nats-io:4222"