apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wui-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - secretName: wui-ingress
    hosts:
    - staging.evntsrc.io
  rules:
  - host: staging.evntsrc.io
    http:
      paths:
      - backend:
          serviceName: wui
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wui
spec:
  ports:
  - port: 80
    name: http
  selector:
    run: wui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
        run: wui
        app: wui
        service: wui
        tier: frontend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: wui
        image: asia.gcr.io/evntsrc-io/wui:latest
        ports:
        - containerPort: 80