// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: event.proto

/*
	Package protos is a generated protocol buffer package.

	It is generated from these files:
		event.proto

	It has these top-level messages:
		Event
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import time "time"

import types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	ID           string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"eventId" bson:"_id"`
	Stream       int32             `protobuf:"varint,2,opt,name=Stream,proto3" json:"stream"`
	Time         *time.Time        `protobuf:"bytes,3,opt,name=Time,stdtime" json:"eventTime"`
	Type         string            `protobuf:"bytes,4,opt,name=Type,proto3" json:"eventType"`
	TypeVersion  string            `protobuf:"bytes,5,opt,name=TypeVersion,proto3" json:"eventTypeVersion"`
	CEVersion    string            `protobuf:"bytes,6,opt,name=CEVersion,proto3" json:"cloudEventVersion"`
	Source       string            `protobuf:"bytes,7,opt,name=Source,proto3" json:"eventSource"`
	Subject      string            `protobuf:"bytes,8,opt,name=Subject,proto3" json:"eventSubject"`
	Acknowledged *time.Time        `protobuf:"bytes,9,opt,name=Acknowledged,stdtime" json:"eventAcknowledged"`
	Metadata     map[string]string `protobuf:"bytes,10,rep,name=Metadata" json:"extensions" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContentType  string            `protobuf:"bytes,11,opt,name=ContentType,proto3" json:"contentType"`
	Data         []byte            `protobuf:"bytes,12,opt,name=Data,proto3" json:"data,string"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptorEvent, []int{0} }

func (m *Event) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Event) GetStream() int32 {
	if m != nil {
		return m.Stream
	}
	return 0
}

func (m *Event) GetTime() *time.Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetTypeVersion() string {
	if m != nil {
		return m.TypeVersion
	}
	return ""
}

func (m *Event) GetCEVersion() string {
	if m != nil {
		return m.CEVersion
	}
	return ""
}

func (m *Event) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Event) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Event) GetAcknowledged() *time.Time {
	if m != nil {
		return m.Acknowledged
	}
	return nil
}

func (m *Event) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (*Event) XXX_MessageName() string {
	return "evntsrc.event.Event"
}
func init() {
	proto.RegisterType((*Event)(nil), "evntsrc.event.Event")
}
func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if m.Stream != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.Stream))
	}
	if m.Time != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(types.SizeOfStdTime(*m.Time)))
		n1, err := types.StdTimeMarshalTo(*m.Time, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if len(m.TypeVersion) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.TypeVersion)))
		i += copy(dAtA[i:], m.TypeVersion)
	}
	if len(m.CEVersion) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.CEVersion)))
		i += copy(dAtA[i:], m.CEVersion)
	}
	if len(m.Source) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Source)))
		i += copy(dAtA[i:], m.Source)
	}
	if len(m.Subject) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Subject)))
		i += copy(dAtA[i:], m.Subject)
	}
	if m.Acknowledged != nil {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(types.SizeOfStdTime(*m.Acknowledged)))
		n2, err := types.StdTimeMarshalTo(*m.Acknowledged, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if len(m.Metadata) > 0 {
		for k, _ := range m.Metadata {
			dAtA[i] = 0x52
			i++
			v := m.Metadata[k]
			mapSize := 1 + len(k) + sovEvent(uint64(len(k))) + 1 + len(v) + sovEvent(uint64(len(v)))
			i = encodeVarintEvent(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintEvent(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintEvent(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.ContentType) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ContentType)))
		i += copy(dAtA[i:], m.ContentType)
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Event) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Stream != 0 {
		n += 1 + sovEvent(uint64(m.Stream))
	}
	if m.Time != nil {
		l = types.SizeOfStdTime(*m.Time)
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.TypeVersion)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.CEVersion)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Acknowledged != nil {
		l = types.SizeOfStdTime(*m.Acknowledged)
		n += 1 + l + sovEvent(uint64(l))
	}
	if len(m.Metadata) > 0 {
		for k, v := range m.Metadata {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovEvent(uint64(len(k))) + 1 + len(v) + sovEvent(uint64(len(v)))
			n += mapEntrySize + 1 + sovEvent(uint64(mapEntrySize))
		}
	}
	l = len(m.ContentType)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stream", wireType)
			}
			m.Stream = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stream |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Time == nil {
				m.Time = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TypeVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CEVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CEVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Acknowledged", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Acknowledged == nil {
				m.Acknowledged = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.Acknowledged, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthEvent
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthEvent
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipEvent(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthEvent
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Metadata[mapkey] = mapvalue
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEvent
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEvent(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEvent = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("event.proto", fileDescriptorEvent) }

var fileDescriptorEvent = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x41, 0x6f, 0xd3, 0x3c,
	0x18, 0xc7, 0x5f, 0x77, 0x6d, 0xb7, 0x3a, 0xed, 0x4b, 0x6b, 0x0d, 0x29, 0xf4, 0x90, 0x94, 0x72,
	0xa0, 0x20, 0x48, 0xc4, 0x26, 0x21, 0xb4, 0x9d, 0xd6, 0xb5, 0x42, 0x3d, 0xc0, 0xc1, 0xad, 0x90,
	0xe0, 0x82, 0xd2, 0xc4, 0x0b, 0x61, 0xa9, 0x1d, 0x25, 0x4e, 0x47, 0xbf, 0x05, 0x47, 0x3e, 0x0d,
	0xe2, 0xb8, 0x23, 0x9f, 0x20, 0xa0, 0xf6, 0x96, 0x23, 0x9f, 0x00, 0xe5, 0x49, 0xb3, 0xb4, 0x27,
	0x4e, 0xb6, 0x9f, 0xe7, 0xf7, 0x7f, 0xfc, 0xf8, 0x6f, 0x1b, 0x2b, 0x6c, 0xc9, 0xb8, 0x34, 0x82,
	0x50, 0x48, 0x41, 0x5a, 0x6c, 0xc9, 0x65, 0x14, 0xda, 0x06, 0x04, 0xbb, 0xcf, 0x5d, 0x4f, 0x7e,
	0x8a, 0xe7, 0x86, 0x2d, 0x16, 0xa6, 0x2b, 0x5c, 0x61, 0x02, 0x35, 0x8f, 0xaf, 0x60, 0x05, 0x0b,
	0x98, 0xe5, 0xea, 0xee, 0xf9, 0x1e, 0xee, 0x5b, 0xdc, 0x2d, 0x05, 0x81, 0x5c, 0x05, 0x2c, 0x32,
	0xa5, 0xb7, 0x60, 0x91, 0xb4, 0x16, 0x41, 0x39, 0xcb, 0xc5, 0xfd, 0xef, 0x35, 0x5c, 0x1b, 0x67,
	0xbb, 0x92, 0x27, 0xb8, 0x32, 0x19, 0xa9, 0xa8, 0x87, 0x06, 0x8d, 0xe1, 0x83, 0x34, 0xd1, 0x0f,
	0xa1, 0x99, 0x89, 0xf3, 0x27, 0xd1, 0xf1, 0x3c, 0x12, 0xfc, 0xac, 0xff, 0xd1, 0x73, 0xfa, 0xb4,
	0x32, 0x19, 0x91, 0x3e, 0xae, 0x4f, 0x65, 0xc8, 0xac, 0x85, 0x5a, 0xe9, 0xa1, 0x41, 0x6d, 0x88,
	0xd3, 0x44, 0xaf, 0x47, 0x10, 0xa1, 0xdb, 0x0c, 0xb9, 0xc0, 0xd5, 0x99, 0xb7, 0x60, 0xea, 0x41,
	0x0f, 0x0d, 0x94, 0x93, 0xae, 0xe1, 0x0a, 0xe1, 0xfa, 0xcc, 0x28, 0x3a, 0x33, 0x66, 0x45, 0x23,
	0xc3, 0x4e, 0x9a, 0xe8, 0x0d, 0xd8, 0x2c, 0x8b, 0x7d, 0xfd, 0xa5, 0x23, 0x0a, 0x52, 0xf2, 0x10,
	0x57, 0x67, 0xab, 0x80, 0xa9, 0x55, 0xe8, 0xa9, 0x55, 0x62, 0xab, 0x80, 0x51, 0x48, 0x91, 0x97,
	0x58, 0xc9, 0xc6, 0x77, 0x2c, 0x8c, 0x3c, 0xc1, 0xd5, 0x1a, 0x90, 0xc7, 0x69, 0xa2, 0xb7, 0xef,
	0xc8, 0x6d, 0x8e, 0xee, 0x82, 0xe4, 0x14, 0x37, 0x2e, 0xc7, 0x85, 0xaa, 0x0e, 0xaa, 0xfb, 0x69,
	0xa2, 0x77, 0x6c, 0x5f, 0xc4, 0x0e, 0xf8, 0x51, 0xc8, 0x4a, 0x8e, 0x3c, 0xc6, 0xf5, 0xa9, 0x88,
	0x43, 0x9b, 0xa9, 0x87, 0xa0, 0xb8, 0x97, 0x26, 0x7a, 0x7e, 0x8f, 0x79, 0x98, 0x6e, 0xd3, 0xe4,
	0x29, 0x3e, 0x9c, 0xc6, 0xf3, 0xcf, 0xcc, 0x96, 0xea, 0x11, 0x90, 0xed, 0x34, 0xd1, 0x9b, 0x39,
	0x99, 0xc7, 0x69, 0x01, 0x90, 0xf7, 0xb8, 0x79, 0x61, 0x5f, 0x73, 0x71, 0xe3, 0x33, 0xc7, 0x65,
	0x8e, 0xda, 0xf8, 0xa7, 0x5f, 0xd9, 0xe5, 0x74, 0xa0, 0xd8, 0xae, 0x10, 0x7c, 0xdb, 0x2b, 0x45,
	0xde, 0xe2, 0xa3, 0x37, 0x4c, 0x5a, 0x8e, 0x25, 0x2d, 0x15, 0xf7, 0x0e, 0x06, 0xca, 0x49, 0xdf,
	0xd8, 0x7b, 0x69, 0x06, 0x9c, 0xd4, 0x28, 0xa0, 0x31, 0x97, 0xe1, 0x6a, 0xf8, 0x7f, 0x9a, 0xe8,
	0x98, 0x7d, 0x91, 0x8c, 0x67, 0x87, 0x8e, 0xe8, 0x5d, 0x0d, 0xf2, 0x02, 0x2b, 0x97, 0x82, 0xcb,
	0xad, 0xaf, 0xaa, 0x52, 0x9a, 0x60, 0x97, 0x61, 0xba, 0xcb, 0x90, 0x47, 0xb8, 0x3a, 0xca, 0xb6,
	0x6f, 0xf6, 0xd0, 0xa0, 0x99, 0xb3, 0x59, 0xa9, 0x67, 0x91, 0x0c, 0x3d, 0xee, 0x52, 0x48, 0x76,
	0xcf, 0x71, 0x6b, 0xaf, 0x05, 0xd2, 0xc6, 0x07, 0xd7, 0x6c, 0x95, 0xbf, 0x45, 0x9a, 0x4d, 0xc9,
	0x31, 0xae, 0x2d, 0x2d, 0x3f, 0x66, 0xf0, 0xe0, 0x1a, 0x34, 0x5f, 0x9c, 0x55, 0x5e, 0xa1, 0xe1,
	0xeb, 0xdb, 0xb5, 0x86, 0x7e, 0xae, 0x35, 0xf4, 0x7b, 0xad, 0xa1, 0x6f, 0x1b, 0xed, 0xbf, 0x1f,
	0x1b, 0x0d, 0xdd, 0x6e, 0x34, 0xf4, 0x61, 0xf7, 0x1b, 0x49, 0xfb, 0xea, 0xc6, 0xdc, 0x9e, 0xdd,
	0xf4, 0xb8, 0x64, 0x21, 0xb7, 0x7c, 0x13, 0x4c, 0xc8, 0x3f, 0x4b, 0x34, 0xaf, 0xc3, 0x78, 0xfa,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x10, 0xc4, 0xfa, 0xea, 0x9a, 0x03, 0x00, 0x00,
}
