/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.evntsrc.ttlscheduler.Binding');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.evntsrc.ttlscheduler.Node');
goog.require('proto.evntsrc.ttlscheduler.Stream');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evntsrc.ttlscheduler.Binding = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.evntsrc.ttlscheduler.Binding, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.evntsrc.ttlscheduler.Binding.displayName = 'proto.evntsrc.ttlscheduler.Binding';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evntsrc.ttlscheduler.Binding.prototype.toObject = function(opt_includeInstance) {
  return proto.evntsrc.ttlscheduler.Binding.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evntsrc.ttlscheduler.Binding} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evntsrc.ttlscheduler.Binding.toObject = function(includeInstance, msg) {
  var f, obj = {
    stream: (f = msg.getStream()) && proto.evntsrc.ttlscheduler.Stream.toObject(includeInstance, f),
    node: (f = msg.getNode()) && proto.evntsrc.ttlscheduler.Node.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evntsrc.ttlscheduler.Binding}
 */
proto.evntsrc.ttlscheduler.Binding.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evntsrc.ttlscheduler.Binding;
  return proto.evntsrc.ttlscheduler.Binding.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evntsrc.ttlscheduler.Binding} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evntsrc.ttlscheduler.Binding}
 */
proto.evntsrc.ttlscheduler.Binding.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.evntsrc.ttlscheduler.Stream;
      reader.readMessage(value,proto.evntsrc.ttlscheduler.Stream.deserializeBinaryFromReader);
      msg.setStream(value);
      break;
    case 2:
      var value = new proto.evntsrc.ttlscheduler.Node;
      reader.readMessage(value,proto.evntsrc.ttlscheduler.Node.deserializeBinaryFromReader);
      msg.setNode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evntsrc.ttlscheduler.Binding.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evntsrc.ttlscheduler.Binding.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evntsrc.ttlscheduler.Binding} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evntsrc.ttlscheduler.Binding.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStream();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.evntsrc.ttlscheduler.Stream.serializeBinaryToWriter
    );
  }
  f = message.getNode();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.evntsrc.ttlscheduler.Node.serializeBinaryToWriter
    );
  }
};


/**
 * optional Stream stream = 1;
 * @return {?proto.evntsrc.ttlscheduler.Stream}
 */
proto.evntsrc.ttlscheduler.Binding.prototype.getStream = function() {
  return /** @type{?proto.evntsrc.ttlscheduler.Stream} */ (
    jspb.Message.getWrapperField(this, proto.evntsrc.ttlscheduler.Stream, 1));
};


/** @param {?proto.evntsrc.ttlscheduler.Stream|undefined} value */
proto.evntsrc.ttlscheduler.Binding.prototype.setStream = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.evntsrc.ttlscheduler.Binding.prototype.clearStream = function() {
  this.setStream(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.evntsrc.ttlscheduler.Binding.prototype.hasStream = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Node node = 2;
 * @return {?proto.evntsrc.ttlscheduler.Node}
 */
proto.evntsrc.ttlscheduler.Binding.prototype.getNode = function() {
  return /** @type{?proto.evntsrc.ttlscheduler.Node} */ (
    jspb.Message.getWrapperField(this, proto.evntsrc.ttlscheduler.Node, 2));
};


/** @param {?proto.evntsrc.ttlscheduler.Node|undefined} value */
proto.evntsrc.ttlscheduler.Binding.prototype.setNode = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.evntsrc.ttlscheduler.Binding.prototype.clearNode = function() {
  this.setNode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.evntsrc.ttlscheduler.Binding.prototype.hasNode = function() {
  return jspb.Message.getField(this, 2) != null;
};


